# Where should we write the GIF?
Output .github/img/demo.gif

Set FontFamily "MesloLGL Nerd Font"
Set TypingSpeed 80ms # 500ms

Set FontSize 20
Set Width 1600
Set Height 800

Type "pnpm start"
Sleep 400ms
Enter

# Enter GoTo Screen
Sleep 3s
Type "g"
Sleep 2s
Type "/Users/techsquidtv/Documents/BlenderQ
Sleep 2s
Enter

# Select Directory
Sleep 3s
Type " "
Sleep 3s

# Edit output
Type "a"
Sleep 2s
Type "/tmp/${NAME}/cube####${EXT}"
Sleep 2s
Enter

# Admire the output for a bit.
Sleep 8s